# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

Key.create(char: 'Command')
Key.create(char: 'Shift')
Key.create(char: 'Delete')
Key.create(char: 'Option')
Key.create(char: 'Ctrl')
Key.create(char: 'Q')
Key.create(char: 'W')
Key.create(char: 'E')
Key.create(char: 'R')
Key.create(char: 'T')
Key.create(char: 'Y')
Key.create(char: 'U')
Key.create(char: 'I')
Key.create(char: 'O')
Key.create(char: 'P')
Key.create(char: 'S')
Key.create(char: 'D')
Key.create(char: 'F')
Key.create(char: 'G')
Key.create(char: 'H')
Key.create(char: 'J')
Key.create(char: 'K')
Key.create(char: 'L')
Key.create(char: 'Z')
Key.create(char: 'X')
Key.create(char: 'C')
Key.create(char: 'V')
Key.create(char: 'B')
Key.create(char: 'N')
Key.create(char: 'M')
Key.create(char: '<')
Key.create(char: '>')
Key.create(char: ',')
Key.create(char: '.')
Key.create(char: ':')
Key.create(char: ';')
Key.create(char: '{')
Key.create(char: '}')
Key.create(char: '[')
Key.create(char: ']')
Key.create(char: '|')
Key.create(char: '+')
Key.create(char: '=')
Key.create(char: '-')
Key.create(char: '±')
Key.create(char: '§')
Key.create(char: '1')
Key.create(char: '!')
Key.create(char: '2')
Key.create(char: '@')
Key.create(char: '3')
Key.create(char: '#')
Key.create(char: '4')
Key.create(char: '$')
Key.create(char: '5')
Key.create(char: '%')
Key.create(char: '6')
Key.create(char: 'ˆ')
Key.create(char: '7')
Key.create(char: '&')
Key.create(char: '8')
Key.create(char: '*')
Key.create(char: '9')
Key.create(char: '0')
Key.create(char: ')')

mac = So.create(name: 'Mac OS', img: File.open(File.join(Rails.root, './app/assets/images/macos.jpg')))
windows = So.create(name: 'Windows', img: File.open(File.join(Rails.root, './app/assets/images/windows.jpg')))
ubuntu = So.create(name: 'Ubuntu', img: File.open(File.join(Rails.root, './app/assets/images/ubuntu.jpg')))

App.create!(so: mac, name: 'Mac OS', img: File.open(File.join(Rails.root, './app/assets/images/macos.jpg')))
App.create!(so: windows, name: 'Windows', img: File.open(File.join(Rails.root, './app/assets/images/windows.jpg')))
App.create!(so: ubuntu, name: 'Ubuntu', img: File.open(File.join(Rails.root, './app/assets/images/ubuntu.jpg')))