# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

Code.create(char: 'Command')
Code.create(char: 'Shift')
Code.create(char: 'Delete')
Code.create(char: 'Option')
Code.create(char: 'Ctrl')
Code.create(char: 'Q')
Code.create(char: 'W')
Code.create(char: 'E')
Code.create(char: 'R')
Code.create(char: 'T')
Code.create(char: 'Y')
Code.create(char: 'U')
Code.create(char: 'I')
Code.create(char: 'O')
Code.create(char: 'P')
Code.create(char: 'S')
Code.create(char: 'D')
Code.create(char: 'F')
Code.create(char: 'G')
Code.create(char: 'H')
Code.create(char: 'J')
Code.create(char: 'K')
Code.create(char: 'L')
Code.create(char: 'Z')
Code.create(char: 'X')
Code.create(char: 'C')
Code.create(char: 'V')
Code.create(char: 'B')
Code.create(char: 'N')
Code.create(char: 'M')
Code.create(char: '<')
Code.create(char: '>')
Code.create(char: ',')
Code.create(char: '.')
Code.create(char: ':')
Code.create(char: ';')
Code.create(char: '{')
Code.create(char: '}')
Code.create(char: '[')
Code.create(char: ']')
Code.create(char: '|')
Code.create(char: '+')
Code.create(char: '=')
Code.create(char: '-')
Code.create(char: '±')
Code.create(char: '§')
Code.create(char: '1')
Code.create(char: '!')
Code.create(char: '2')
Code.create(char: '@')
Code.create(char: '3')
Code.create(char: '#')
Code.create(char: '4')
Code.create(char: '$')
Code.create(char: '5')
Code.create(char: '%')
Code.create(char: '6')
Code.create(char: 'ˆ')
Code.create(char: '7')
Code.create(char: '&')
Code.create(char: '8')
Code.create(char: '*')
Code.create(char: '9')
Code.create(char: '0')
Code.create(char: ')')

mac = So.create(name: 'Mac OS', img: File.open(File.join(Rails.root, './app/assets/images/macos.jpg')))
windows = So.create(name: 'Windows', img: File.open(File.join(Rails.root, './app/assets/images/windows.jpg')))
ubuntu = So.create(name: 'Ubuntu', img: File.open(File.join(Rails.root, './app/assets/images/ubuntu.jpg')))

App.create!(so: mac, name: 'Mac OS', img: File.open(File.join(Rails.root, './app/assets/images/macos.jpg')))
App.create!(so: windows, name: 'Windows', img: File.open(File.join(Rails.root, './app/assets/images/windows.jpg')))
App.create!(so: ubuntu, name: 'Ubuntu', img: File.open(File.join(Rails.root, './app/assets/images/ubuntu.jpg')))